[[bond]]
source = "tpknam1qqaucurxsntmwgvtvrr3v4k8fffm0w8d4yfgte2e5ud7v72ta704uxpfg9a"
validator = "tnam1qydvhqdu2q2vrgvju2ngpt6yhrehu525pus6m28p"
amount = "2570"

[bond.signatures]
tpknam1qqaucurxsntmwgvtvrr3v4k8fffm0w8d4yfgte2e5ud7v72ta704uxpfg9a = "signam1qr2u5vsw3wl4pdyxqyjntqsjsqfvw990weemeznztl2xghpsuvquksupdurpvlujeek5n5ueuhd2q6ny0thwd3rat76cmr09slrve4q2tked0t"
